sudo: required
language: c
os: linux
matrix:
  include:
    # works on Precise and Trusty
    - name: "clang-3.4"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.4 main"
            - key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-3.4
      env:
        - MATRIX_EVAL="CC=clang-3.4" # For clang 3.4

    # works on Precise and Trusty
    - name: "clang-3.5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
      env:
        - MATRIX_EVAL="CC=clang-3.5"

    # works on Precise and Trusty
    - name: "clang-3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6"

    # works on Precise and Trusty
    - name: "clang-3.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7"

    # works on Precise and Trusty
    - name: "clang-3.8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8"

    # works on Trusty
    - name: "clang-3.9"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9"

    # works on Trusty
    - name: "clang-4.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0"

    # works on Trusty
    - name: "clang-5.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"

    # works on Trusty
    - name: "clang-6.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo ln -s "`which ${CC}`" /usr/bin/clang

before_script:
  - clang --version

script:
  - make